[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
include = ["src", "artifacts", "force_rebuild.txt"]

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
