[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
include = ["src", "artifacts"]

[deploy]
startCommand = "deno run -A src/main.ts"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
